using System;
using System.Diagnostics;
using System.Text;
using System.Threading.Tasks;
using LINQAnalyzer.Application.Interfaces;
using LINQAnalyzer.Domain.Models;

namespace LINQAnalyzer.Infrastructure.Agents;

public class BenchmarkAgent : IBenchmarkAgent
{
    public Task<BenchmarkResult> BenchmarkSnippetAsync(string codeSnippet)
    {
        var sw = Stopwatch.StartNew();
        long initialMemory = GC.GetAllocatedBytesForCurrentThread();

        // Analyze query patterns to estimate allocation and execution impact
        bool hasToListInLoop = codeSnippet.Contains(".ToList()") || codeSnippet.Contains(".ToArray()");
        bool hasSelectAll = codeSnippet.Contains("Select(x => x)") || !codeSnippet.Contains("Select(");
        bool hasCartesianJoin = codeSnippet.Contains("SelectMany") || (codeSnippet.Contains("from") && codeSnippet.Split("from").Length > 2);

        long estimatedBytes = 1024; // Baseline overhead
        if (hasToListInLoop) estimatedBytes += 524_288; // ~500 KB estimated for in-memory materialize
        if (hasSelectAll) estimatedBytes += 131_072;     // ~128 KB extra columns overhead
        if (hasCartesianJoin) estimatedBytes += 2_097_152; // ~2 MB potential N+1 / join multiplier

        sw.Stop();
        
        // Mock SQL translation output based on query structure
        string simulatedSql = GenerateSimulatedSql(codeSnippet);
        double executionTimeMs = Math.Round(sw.Elapsed.TotalMilliseconds + (estimatedBytes / 50_000.0), 2);

        return Task.FromResult(new BenchmarkResult(
            EstimatedAllocatedBytes: estimatedBytes,
            ExecutionTimeMs: executionTimeMs,
            ExecutedSql: simulatedSql
        ));
    }

    /// <summary>
    /// Generates complete, compilable BenchmarkDotNet C# source code comparing the original snippet against the AI refactored code.
    /// </summary>
    public string GenerateBenchmarkHarness(DiscoveredIssue issue, string refactoredCode)
    {
        string backticks = "```";
        
        // Clean up markdown code blocks if present in snippets
        string cleanOriginal = issue.Snippet.Replace(backticks + "csharp", "").Replace(backticks, "").Trim();
        string cleanRefactored = refactoredCode.Replace(backticks + "csharp", "").Replace(backticks, "").Trim();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Auto-generated BenchmarkDotNet Test Harness for LINQ Performance Analysis");
        sb.AppendLine($"// Rule ID: {issue.RuleId} ({issue.RuleName})");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using BenchmarkDotNet.Attributes;");
        sb.AppendLine("using BenchmarkDotNet.Running;");
        sb.AppendLine();
        sb.AppendLine("namespace LINQAnalyzer.Benchmarks;");
        sb.AppendLine();
        sb.AppendLine("[MemoryDiagnoser]");
        sb.AppendLine("[Orderer(BenchmarkDotNet.Order.SummaryOrderPolicy.FastestToSlowest)]");
        sb.AppendLine("[RankColumn]");
        sb.AppendLine($"public class {SanitizeClassName(issue.RuleId)}Benchmark");
        sb.AppendLine("{");
        sb.AppendLine("    private List<TestEntity> _dataset = new();");
        sb.AppendLine();
        sb.AppendLine("    [GlobalSetup]");
        sb.AppendLine("    public void Setup()");
        sb.AppendLine("    {");
        sb.AppendLine("        // Seed mock dataset for benchmark execution");
        sb.AppendLine("        _dataset = Enumerable.Range(1, 10_000).Select(i => new TestEntity");
        sb.AppendLine("        {");
        sb.AppendLine("            Id = i,");
        sb.AppendLine("            Name = $\"Entity_{i}\",");
        sb.AppendLine("            IsActive = i % 2 == 0,");
        sb.AppendLine("            CreatedDate = DateTime.UtcNow.AddDays(-i)");
        sb.AppendLine("        }).ToList();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    [Benchmark(Baseline = true, Description = \"Original Code (Anti-Pattern)\")]");
        sb.AppendLine("    public void OriginalCode()");
        sb.AppendLine("    {");
        sb.AppendLine("        var data = _dataset.AsQueryable();");
        sb.AppendLine($"        // Original Code (Line {issue.LineNumber})");
        sb.AppendLine($"        {IndentCode(cleanOriginal, "        ")}");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    [Benchmark(Description = \"AI Refactored Code (Optimized)\")]");
        sb.AppendLine("    public void RefactoredCode()");
        sb.AppendLine("    {");
        sb.AppendLine("        var data = _dataset.AsQueryable();");
        sb.AppendLine("        // Optimized Solution");
        sb.AppendLine($"        {IndentCode(cleanRefactored, "        ")}");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("public class TestEntity");
        sb.AppendLine("{");
        sb.AppendLine("    public int Id { get; set; }");
        sb.AppendLine("    public string Name { get; set; } = string.Empty;");
        sb.AppendLine("    public bool IsActive { get; set; }");
        sb.AppendLine("    public DateTime CreatedDate { get; set; }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string SanitizeClassName(string ruleId)
    {
        return ruleId.Replace("-", "_").Replace(".", "_");
    }

    private static string IndentCode(string code, string indentation)
    {
        string[] lines = code.Split(new[] { "\r\n", "\r", "\n" }, StringSplitOptions.None);
        return string.Join(Environment.NewLine + indentation, lines);
    }

    private static string GenerateSimulatedSql(string snippet)
    {
        if (snippet.Contains("Count() > 0") || snippet.Contains("Count() != 0"))
        {
            return "-- Anti-Pattern Detected: COUNT(*) fetches full result set\nSELECT COUNT(*)\nFROM [Entities] AS [e]";
        }
        if (snippet.Contains(".Where("))
        {
            return "SELECT [e].[Id], [e].[Name], [e].[CreatedDate]\nFROM [Entities] AS [e]\nWHERE [e].[IsActive] = 1";
        }
        return "SELECT [e].[Id], [e].[ColumnA], [e].[ColumnB]\nFROM [Entities] AS [e]";
    }
}